apiVersion: batch/v1
kind: Job
metadata:
  name: shopping-cart-load-driver
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumes:
        - name: shopping-cart-load-driver-pvc
          persistentVolumeClaim:
            claimName: shopping-cart-load-driver-pvc
      containers:
        - name: shopping-cart-load-driver
          image: northamerica-northeast2-docker.pkg.dev/scylla-cassandra-comparison/load-test/shopping-cart-load-test-driver:0.3.0-SNAPSHOT # note
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/mnt/simulation-data"
              name: shopping-cart-load-driver-pvc
          env:
            - name: RANDOM_PAYLOAD_SIZE
              value: "50"  # value in bytes
            - name: TARGET_HOST
              value: "shopping-cart-service"  # service hostname exposed by shopping-cart-service
            - name: TARGET_PORT
              value: "8101"
            - name: TEST_DURATION
              value: "180.minutes"  # 10800.seconds
            - name: USERS_PER_SECOND
              value: "100"
            - name: RAMP_FROM
              value: "1"
            - name: RAMP_TO
              value: "100"
            - name: RAMP_OVER
              value: "5.minutes"
            - name: GATLING_GRPC_LOG_LEVEL
              value: "DEBUG"  # will log failed responses
            - name: RESULT_BASE_DIR
              value: "/mnt/simulation-data" # should pick/set a more appropriate mount path
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: "30000m"
              memory: "24Gi"
            limits:
              memory: "24Gi"
      restartPolicy: Never
  backoffLimit: 4
  completions: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopping-cart-load-driver-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: shopping-cart-load-driver-pv
  resources:
    requests:
      storage: 1Ti
---
# This PV is a common, persistent volume to collect simulation results of load tests across nodes, runs.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shopping-cart-load-driver-pv
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  network: default
