apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
  labels:
    app: shopping-cart-service
spec:
  selector:
    app: shopping-cart-service
  ports:
    - name: shopping-cart-service-grpc
      protocol: TCP
      port: 8101
      targetPort: grpc
    - name: metrics
      protocol: TCP
      port: 9001
      targetPort: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-service
  labels:
    app: shopping-cart-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-cart-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shopping-cart-service
    spec:
      volumes:
        - name: shopping-cart-service-storage
          persistentVolumeClaim:
            claimName: shopping-cart-service-pvc
      containers:
        - name: shopping-cart-service
          image: shopping-cart-load-test/shopping-cart-service:0.5.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/mnt/gc-logs"
              #              name: shopping-cart-load-driver-pvc
              name: shopping-cart-service-storage
          #args: ["-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/mnt/heapdumps/$(POD_NAME).hprof"]
          # Variable-substitution only works for args, not env. The start-script will handle the JVM args correctly.
          args: ["-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/mnt/heapdumps/$(POD_NAME).hprof", "-Xloggc:/mnt/gc-logs/$(POD_NAME)-gc.log"]
          env:
            - name: JAVA_OPTS
              value: >-
                -Dconfig.resource=deployed.conf
                -XX:+UseG1GC
                -XX:+UseStringDeduplication
                -Xmx1500m
                -Xms1500m
                -XX:+PrintFlagsFinal
                -XX:+PrintGCDetails
                -XX:+PrintTenuringDistribution
                -XX:+PrintGCTimeStamps
                -XX:+PrintGCDateStamps
            # this value should stay the same as number of replicas
            - name: REQUIRED_CONTACT_POINT_NR
              value: "3"
            # currently configured to point at cassandra-1 'example' cluster (found in cassandra.yaml)
            - name: CASSANDRA_SEED_NODE
              value: "cassandra-1.cassandra-single:9042"
            - name: CASSANDRA_LOCAL_DATACENTER
              value: "datacenter1"
            - name: RUN_ITEM_POPULARITY_PROJECTION
              value: "false"
            - name: PASSIVATION_ACTIVE_ENTITY_LIMIT
              value: "2000000"
            - name: CASSANDRA_REPLICAS
              value: "3"
            - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: "metadata.labels['app']"
          ports:
            - name: grpc
              containerPort: 8101
            - name: metrics
              containerPort: 9001
            - name: remoting
              containerPort: 2552
            - name: management
              containerPort: 8558
          readinessProbe:
            httpGet:
              port: management
              path: /ready
            periodSeconds: 10
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              port: management
              path: /alive
            periodSeconds: 10
            initialDelaySeconds: 20
            failureThreshold: 10
          resources:
            requests:
              cpu: "250m"
              memory: "1.5G"
            limits:
              memory: "2G"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: akka-discovery-pod-reader
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: akka-discovery-read-pods
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: akka-discovery-pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shopping-cart-service
  labels:
    team: architecture
spec:
  selector:
    matchLabels:
      app: shopping-cart-service
  endpoints:
    - port: metrics
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopping-cart-service-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shopping-cart-service-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    # TODO:  maps to a local directory as demonstration, replace accordingly
    path: "/Users/dkichler/projects/scylla-pov/akka-cqrs-cart-example/shopping-cart-service/gc-logs"
