#FROM grafana/grafana:6.0.2
FROM grafana/grafana:9.2.15

#COPY plugins/cinnamon-prometheus-app /var/lib/grafana/plugins/cinnamon-prometheus-app
COPY plugins/cinnamon-prometheus-app /usr/share/grafana/plugins-bundled/cinnamon-prometheus-app
